# Generated by Django 5.1.3 on 2024-11-25 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_personal_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_team_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
