# Generated by Django 5.1.3 on 2024-12-09 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_personaltask_created_by_and_more'),
        ('teams', '0002_alter_team_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamtask',
            options={'ordering': ['deadline'], 'permissions': [('assign_task', 'Can assign task to user'), ('edit_task', 'Can edit task')]},
        ),
        migrations.AddIndex(
            model_name='teamtask',
            index=models.Index(fields=['deadline'], name='tasks_teamt_deadlin_d6ce26_idx'),
        ),
    ]
