# Generated by Django 5.1.3 on 2024-12-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_teamtask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamtask',
            options={'ordering': ['deadline'], 'permissions': [('assign_task', 'Can assign task to user'), ('edit_task', 'Can edit specific fields of the task')]},
        ),
    ]
